### PR TITLE
Add support for client_id, object_id and ms_res_id query parameters for VmMSI and fixed a bug in AzureCliCredentials

### LINKED ISSUE #58: MsiVmOptions lacks ClientId to support user-assigned managed identities
**Package Version**: 1.1.1
   - [X] **nodejs**
   - **nodejs version**: 10.5.3
   - **os name/version**: Linux (Ubuntu) - AKS
- [ ] **browser**
    - **name/version**: ____
**Describe the bug**
Azure supports two types of Managed Identities for virtual machines: System-assigned, and user-assigned.  The ms-rest-nodeauth library (and its predecessor ms-rest-azure) support system-assigned identities for VMs, but lack support for user-assigned managed identities.

The msiVmTokenCredentials.ts class provides (almost) everything to call the REST API for both identity types, but the MSIVmOptions interface lacks the ability to pass in the optional object_id and/or client_id query string parameters which are required for VMs that have multiple user-assigned managed identities.

For more information, see: 
* https://docs.microsoft.com/en-gb/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http
* https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/msi-tutorial-linux-vm-access-arm#get-an-access-token-using-the-vms-identity-and-use-it-to-call-resource-manager

### PR DESCRIPTION
**Pull request by amarzavery**
- Fixes #58.
- Fixes https://github.com/Azure/azure-sdk-for-node/issues/2284#issuecomment-493786455

### CODE REVIEW

File: lib/credentials/azureCliCredentials.ts [hunk 1]
```diff
@@ -104,9 +144,10 @@ export class AzureCliCredentials implements TokenClientCredentials {
    */
   public async signRequest(webResource: WebResource): Promise<WebResource> {
     const tokenResponse = await this.getToken();
+    const result = `${tokenResponse.tokenType} ${tokenResponse.accessToken}`;
     webResource.headers.set(
       MSRestConstants.HeaderConstants.AUTHORIZATION,
-      `${tokenResponse.tokenType} ${tokenResponse.accessToken}`
+      result
```
Comment (daschult) [inline lib/credentials/azureCliCredentials.ts]: Maybe rename `result` to `headerValue`?

File: lib/credentials/azureCliCredentials.ts [hunk 2]
```diff
@@ -126,15 +167,58 @@ export class AzureCliCredentials implements TokenClientCredentials {
     return this.subscriptionInfo.id !== this.tokenInfo.subscription;
   }
 
+  private _parseToken(): any {
+    try {
+      const base64Url = this.tokenInfo.accessToken.split(".")[1];
+      const base64 = decodeURIComponent(
```
Comment (daschult) [inline lib/credentials/azureCliCredentials.ts]: Please add types for these variables.

File: package.json [hunk 3]
```diff
@@ -5,7 +5,7 @@
     "email": "azsdkteam@microsoft.com",
     "url": "https://github.com/Azure/ms-rest-nodeauth"
   },
-  "version": "1.1.1",
+  "version": "1.2.0",
```
Comment (daschult) [inline package.json]: I know you just released this feature recently, but these are still breaking changes. I'd recommend bumping the version to 2.0.0.
